package Client;

public enum ClientLog {
    CONNECTION_FAILED,
    CONFIG_MISSING,
    NO_RECIPIENTS,
    INVALID_MAIL,
    SERVER_DISCONNECTED,
    SEND_ERROR,
    REQUEST_SUCCESSFUL,
    UNKNOWN_MAIL,
    DELETE_ERROR
}
